"""assemble_variant_buffers: rust vs frozen golden (oracle frozen Phase 5 W5).

All parametrised cases (windows mode matrix, variants mode matrix, empty selection)
are now replayed from the frozen golden generated by generate_goldens.py and
cross-checked against numba at generation time.
"""

from __future__ import annotations

import pytest

from tests.parity import _golden

pytestmark = pytest.mark.parity


def test_assemble_variant_buffers_golden():
    """Rust assemble_variant_buffers must equal the frozen golden for all mode combinations."""
    cases = _golden.load_golden("assemble_variant_buffers")
    assert cases, "empty golden"
    _golden.replay_dict("assemble_variant_buffers", cases)
