"""Shared fixtures for the GenVarLoader test suite.

Centralizes paths to on-disk artifacts under ``tests/data/``. Test files
should import these via fixture injection rather than constructing paths
or opening datasets at module scope.

Fixtures here intentionally yield *paths*, not opened Datasets. Opening
a Dataset costs real time; pushing that decision to the test (or to a
small, locally scoped fixture in the test file) keeps fixture cost
predictable. Where a session-scoped opened Dataset is genuinely useful,
prefer adding it inside the integration test file that needs it.
"""

import subprocess
from pathlib import Path

import pytest

# --- root paths --------------------------------------------------------------


@pytest.fixture(scope="session")
def tests_dir() -> Path:
    return Path(__file__).resolve().parent


@pytest.fixture(scope="session")
def data_dir(tests_dir: Path) -> Path:
    return tests_dir / "data"


# --- reference -------------------------------------------------------------


@pytest.fixture(scope="session")
def ref_fasta(data_dir: Path) -> Path:
    """bgzipped synthetic reference used by the toy datasets (generated by `gen`)."""
    return data_dir / "fasta" / "synthetic.fa.bgz"


@pytest.fixture(scope="session")
def reference(ref_fasta: Path):
    """Opened ``gvl.Reference`` (metadata-only, ``in_memory=False``).

    Carve-out vs. the "yield paths, not Datasets" convention: opening a
    Reference with ``in_memory=False`` is metadata-only (FAI/GZI read),
    not the expensive bytes-loading path. Multiple tests need this exact
    construction, so centralizing it here removes duplication without
    violating the spirit of the convention.
    """
    import genvarloader as gvl

    return gvl.Reference.from_path(ref_fasta, in_memory=False)


# --- hg38 reference (1kg slow tier) -----------------------------------------


@pytest.fixture(scope="session")
def hg38_ref_fasta(data_dir: Path) -> Path:
    """Minimal hg38 (chr21 + chr22) used by the 1kg slow tier.

    Built by ``pixi run -e dev gen-1kg`` (see
    ``tests/data/generate_1kg_ground_truth.py::provision_minimal_hg38``). The
    toy datasets use the synthetic chr1/chr2 reference instead; the 1kg data is
    on chr21/chr22 and needs real hg38 coordinates. Tests that depend on this
    should ``pytest.skip`` when it is absent.
    """
    return data_dir / "fasta" / "hg38.fa.bgz"


@pytest.fixture(scope="session")
def hg38_reference(hg38_ref_fasta: Path):
    """Opened ``gvl.Reference`` over the minimal hg38 (chr21 + chr22).

    Skips the depending test when the reference is absent (it is only built by
    the ``gen-1kg`` task, not the default ``gen``)."""
    import genvarloader as gvl

    if not hg38_ref_fasta.exists():
        pytest.skip("missing hg38 reference; run pixi run -e dev gen-1kg")
    return gvl.Reference.from_path(hg38_ref_fasta, in_memory=False)


# --- session-scoped generated case (Phase 2) --------------------------------


@pytest.fixture(scope="session")
def synthetic_case(tmp_path_factory):
    """Build one standardized (chr1/chr2, s0..s2) case per session via the
    shared build_case pipeline. Replaces the committed consensus/ +
    phased_dataset.*.gvl/ artifacts; the path fixtures below yield from it."""
    import sys

    builders = Path(__file__).resolve().parent / "_builders"
    if str(builders) not in sys.path:
        sys.path.insert(0, str(builders))
    import polars as pl
    from case import SEQ_LEN, build_case, session_document, session_reference

    spec = session_reference()
    doc = session_document(spec)
    extra = pl.DataFrame(
        {
            "chrom": ["chr1", "chr1"],
            "start": [1010696, 500_000],
            "end": [1010696 + SEQ_LEN, 500_000 + SEQ_LEN],
        }
    )
    workdir = tmp_path_factory.mktemp("synthetic_case")
    return build_case(spec, doc, workdir, extra_regions=extra)


# --- toy phased datasets (one per variant source) ----------------------------


@pytest.fixture(scope="session")
def phased_vcf_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["vcf"]


@pytest.fixture(scope="session")
def phased_pgen_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["pgen"]


@pytest.fixture(scope="session")
def phased_svar_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["svar"]


# --- SVAR2 dataset (opens as Svar2Haps) --------------------------------------
#
# Deliberately NOT built from `synthetic_case`/`reference` above: those cover
# the SVAR1/VCF/PGEN `Haps` read path. `Svar2Haps` is a structurally different
# reconstructor (reads a `.svar2` store read-bound via Rust FFI, see
# docs/superpowers/specs/2026-07-23-phase0-realcorpus-findings.md), and the
# tiny fixture below (mirroring tests/dataset/test_svar2_dataset.py::_src /
# svar2_fixture, already verified in that Phase-0 doc to reproduce #315) is
# sufficient -- the defect is content-independent. It needs its own matching
# reference (a different contig/length than the shared `reference` fixture),
# hence the paired `svar2_slot_reference` fixture below rather than reuse of
# `reference`.

# 40 bp reference (chr1). VCF POS (1-based) -> 0-based: SNP@2 (A>G), INS@6
# (C>CAT), dense SNP@9 (G>C, carried by 3 haps), DEL@11 (GTA>G, ilen -2).
_SVAR2_SLOT_REF = "ACAGTACATGGGTACTAGCTAGGCTAACCGGTTAACCGGT"
_SVAR2_SLOT_VCF = """\
##fileformat=VCFv4.2
##contig=<ID=chr1,length=40>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tS0\tS1
chr1\t3\t.\tA\tG\t.\t.\t.\tGT\t1|0\t0|0
chr1\t7\t.\tC\tCAT\t.\t.\t.\tGT\t0|1\t1|1
chr1\t10\t.\tG\tC\t.\t.\t.\tGT\t1|1\t1|0
chr1\t12\t.\tGTA\tG\t.\t.\t.\tGT\t1|1\t0|1
"""


@pytest.fixture(scope="session")
def _svar2_slot_src(tmp_path_factory) -> tuple[Path, Path]:
    """(bcf, ref) reproducing the #315 pinned record class: ordinary SNP,
    insertion, dense SNP, and deletion content over 2 samples -- enough for
    >=1 (region, sample) group with n_variants > 0 (the defect is
    content-independent, see the Phase-0 findings doc)."""
    d = tmp_path_factory.mktemp("svar2_slot_src")
    ref = d / "ref.fa"
    ref.write_text(f">chr1\n{_SVAR2_SLOT_REF}\n")
    subprocess.run(["samtools", "faidx", str(ref)], check=True)

    vcf = d / "in.vcf"
    vcf.write_text(_SVAR2_SLOT_VCF)
    bcf = d / "in.bcf"
    subprocess.run(["bcftools", "view", "-Ob", "-o", str(bcf), str(vcf)], check=True)
    subprocess.run(["bcftools", "index", str(bcf)], check=True)
    return bcf, ref


@pytest.fixture(scope="session")
def svar2_slot_reference(_svar2_slot_src):
    """Opened ``gvl.Reference`` matching `phased_svar2_gvl`'s tiny chr1.

    Carve-out vs. the "yield paths, not Datasets" convention (see module
    docstring): same rationale as `reference` above -- ``in_memory=False`` is
    metadata-only, and the paired dataset fixture needs an exactly-matching
    reference to open against.
    """
    import genvarloader as gvl

    _bcf, ref = _svar2_slot_src
    return gvl.Reference.from_path(ref, in_memory=False)


@pytest.fixture(scope="session")
def phased_svar2_gvl(_svar2_slot_src, tmp_path_factory) -> Path:
    """A gvl dataset written from a ``.svar2`` source -> opens as ``Svar2Haps``.

    Reproduces the Phase-0-pinned record class for #315 (see
    docs/superpowers/specs/2026-07-23-phase0-realcorpus-findings.md): >=1
    (region, sample) group with n_variants > 0 via ordinary SNP/indel content.
    Open with `svar2_slot_reference`, not the shared `reference` fixture (this
    store uses its own tiny reference, see `_svar2_slot_src`). Written with
    ``max_jitter=0``: variant-windows/variants mode raises NotImplementedError
    on an SVAR2 dataset written with max_jitter>0 (no right-clip support).
    """
    import polars as pl
    from genoray import SparseVar2, _core

    import genvarloader as gvl

    bcf, ref = _svar2_slot_src
    store = tmp_path_factory.mktemp("svar2_slot_store") / "store.svar2"
    _core.run_conversion_pipeline(
        str(bcf),
        str(ref),
        ["chr1"],
        str(store),
        ["S0", "S1"],
        25_000,
        2,
        1,
        8 * 1024 * 1024,
    )
    assert (store / "meta.json").exists(), "svar2 conversion did not finish"

    bed = pl.DataFrame(
        {"chrom": ["chr1", "chr1"], "chromStart": [0, 20], "chromEnd": [20, 40]}
    )
    out = tmp_path_factory.mktemp("svar2_slot_gvl") / "ds.gvl"
    gvl.write(
        out,
        bed,
        variants=SparseVar2(store),
        samples=None,
        max_jitter=0,
        overwrite=True,
    )
    return out


# --- 1kg datasets (slow tier) ------------------------------------------------


@pytest.fixture(scope="session")
def kg_dir(data_dir: Path) -> Path:
    return data_dir / "1kg"


@pytest.fixture(scope="session")
def kg_bcf_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.bcf.gvl"


@pytest.fixture(scope="session")
def kg_pgen_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.pgen.gvl"


@pytest.fixture(scope="session")
def kg_svar_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.svar.gvl"


# --- raw inputs / regression artifacts --------------------------------------


@pytest.fixture(scope="session")
def source_bed(data_dir: Path) -> Path:
    return data_dir / "source.bed"


@pytest.fixture(scope="session")
def issue_153_bed(data_dir: Path) -> Path:
    return data_dir / "issue_153.bed"


@pytest.fixture(scope="session")
def issue_153_vcf(data_dir: Path) -> Path:
    return data_dir / "issue_153.vcf"


# --- raw variant source subdirectories --------------------------------------


@pytest.fixture(scope="session")
def vcf_dir(data_dir: Path) -> Path:
    """Directory containing filtered VCF files used as variant sources."""
    return data_dir / "vcf"


@pytest.fixture(scope="session")
def pgen_dir(data_dir: Path) -> Path:
    """Directory containing filtered PGEN files used as variant sources."""
    return data_dir / "pgen"


@pytest.fixture(scope="session")
def filtered_svar(data_dir: Path) -> Path:
    """Pre-built SparseVar dataset used for svar-link and var-filter tests."""
    return data_dir / "filtered.svar"


# --- bigwig tracks -----------------------------------------------------------


@pytest.fixture(scope="session")
def bigwig_dir(data_dir: Path) -> Path:
    """Directory containing sample BigWig files."""
    return data_dir / "bigwig"


# --- ground-truth / consensus directories -----------------------------------


@pytest.fixture(scope="session")
def consensus_dir(synthetic_case) -> Path:
    """Per-haplotype consensus FASTA ground truth, generated per session."""
    return synthetic_case.consensus_dir
