"""Shared fixtures for the GenVarLoader test suite.

Centralizes paths to on-disk artifacts under ``tests/data/``. Test files
should import these via fixture injection rather than constructing paths
or opening datasets at module scope.

Fixtures here intentionally yield *paths*, not opened Datasets. Opening
a Dataset costs real time; pushing that decision to the test (or to a
small, locally scoped fixture in the test file) keeps fixture cost
predictable. Where a session-scoped opened Dataset is genuinely useful,
prefer adding it inside the integration test file that needs it.
"""

from pathlib import Path

import pytest

# --- root paths --------------------------------------------------------------


@pytest.fixture(scope="session")
def tests_dir() -> Path:
    return Path(__file__).resolve().parent


@pytest.fixture(scope="session")
def data_dir(tests_dir: Path) -> Path:
    return tests_dir / "data"


# --- reference -------------------------------------------------------------


@pytest.fixture(scope="session")
def ref_fasta(data_dir: Path) -> Path:
    """bgzipped synthetic reference used by the toy datasets (generated by `gen`)."""
    return data_dir / "fasta" / "synthetic.fa.bgz"


@pytest.fixture(scope="session")
def reference(ref_fasta: Path):
    """Opened ``gvl.Reference`` (metadata-only, ``in_memory=False``).

    Carve-out vs. the "yield paths, not Datasets" convention: opening a
    Reference with ``in_memory=False`` is metadata-only (FAI/GZI read),
    not the expensive bytes-loading path. Multiple tests need this exact
    construction, so centralizing it here removes duplication without
    violating the spirit of the convention.
    """
    import genvarloader as gvl

    return gvl.Reference.from_path(ref_fasta, in_memory=False)


# --- session-scoped generated case (Phase 2) --------------------------------


@pytest.fixture(scope="session")
def synthetic_case(tmp_path_factory):
    """Build one standardized (chr1/chr2, s0..s2) case per session via the
    shared build_case pipeline. Replaces the committed consensus/ +
    phased_dataset.*.gvl/ artifacts; the path fixtures below yield from it."""
    import sys

    builders = Path(__file__).resolve().parent / "_builders"
    if str(builders) not in sys.path:
        sys.path.insert(0, str(builders))
    import polars as pl
    from case import SEQ_LEN, build_case, session_document, session_reference

    spec = session_reference()
    doc = session_document(spec)
    extra = pl.DataFrame(
        {
            "chrom": ["chr1", "chr1"],
            "start": [1010696, 500_000],
            "end": [1010696 + SEQ_LEN, 500_000 + SEQ_LEN],
        }
    )
    workdir = tmp_path_factory.mktemp("synthetic_case")
    return build_case(spec, doc, workdir, extra_regions=extra)


# --- toy phased datasets (one per variant source) ----------------------------


@pytest.fixture(scope="session")
def phased_vcf_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["vcf"]


@pytest.fixture(scope="session")
def phased_pgen_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["pgen"]


@pytest.fixture(scope="session")
def phased_svar_gvl(synthetic_case) -> Path:
    return synthetic_case.gvl_path["svar"]


# --- 1kg datasets (slow tier) ------------------------------------------------


@pytest.fixture(scope="session")
def kg_dir(data_dir: Path) -> Path:
    return data_dir / "1kg"


@pytest.fixture(scope="session")
def kg_bcf_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.bcf.gvl"


@pytest.fixture(scope="session")
def kg_pgen_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.pgen.gvl"


@pytest.fixture(scope="session")
def kg_svar_gvl(kg_dir: Path) -> Path:
    return kg_dir / "phased_1kg.svar.gvl"


# --- raw inputs / regression artifacts --------------------------------------


@pytest.fixture(scope="session")
def source_bed(data_dir: Path) -> Path:
    return data_dir / "source.bed"


@pytest.fixture(scope="session")
def issue_153_bed(data_dir: Path) -> Path:
    return data_dir / "issue_153.bed"


@pytest.fixture(scope="session")
def issue_153_vcf(data_dir: Path) -> Path:
    return data_dir / "issue_153.vcf"


# --- raw variant source subdirectories --------------------------------------


@pytest.fixture(scope="session")
def vcf_dir(data_dir: Path) -> Path:
    """Directory containing filtered VCF files used as variant sources."""
    return data_dir / "vcf"


@pytest.fixture(scope="session")
def pgen_dir(data_dir: Path) -> Path:
    """Directory containing filtered PGEN files used as variant sources."""
    return data_dir / "pgen"


@pytest.fixture(scope="session")
def filtered_svar(data_dir: Path) -> Path:
    """Pre-built SparseVar dataset used for svar-link and var-filter tests."""
    return data_dir / "filtered.svar"


# --- bigwig tracks -----------------------------------------------------------


@pytest.fixture(scope="session")
def bigwig_dir(data_dir: Path) -> Path:
    """Directory containing sample BigWig files."""
    return data_dir / "bigwig"


# --- ground-truth / consensus directories -----------------------------------


@pytest.fixture(scope="session")
def consensus_dir(synthetic_case) -> Path:
    """Per-haplotype consensus FASTA ground truth, generated per session."""
    return synthetic_case.consensus_dir
